#!/bin/bash
# vim: set ft=sh:


stage=$1
repo=$2
gitdir=$3
before=$4
after=$5
user=$6

set -e

if [ -d "$gitdir" ]
then
	cd "$gitdir" || exit 2

	#
	# composer
	#
	# "composer install" only if composer.lock is present AND is in the diff

	composer_update=0
	composererror=0

	if [ ! -d vendor ]
	then
		composer_update=1
	else
		if [ -n "$before" ] && [ -n "$after" ]
		then
			if git diff --name-only $before $after | grep -q ^composer\.lock
			then
				composer_update=1
			fi
		fi
	fi

	if [ -e composer.lock ] && [ $composer_update -gt 0 ]
	then
		unset GIT_DIR
		unset GIT_WORK_TREE
		composererror=1
		echo -e "\033[45m\033[1;36m>= COMPOSER INSTALL <=\033[0m"
		composer=$( which composer )

		if grep -qF '"php" : "7' composer.json
		then
			composer="/usr/bin/php7.1 -d memory_limit=1G /usr/local/bin/composer.phar"
		fi

		if $composer --no-interaction --optimize-autoloader --no-dev --ansi --prefer-dist install
		then
			composererror=0
		else
			composererror=1
		fi

		if [ $composererror -gt 0 ]
		then
			echo -e "\033[41m\033[1mCOMPOSER INSTALL FAILED\033[0m" >&2
			composer validate
			exit 3
		fi
	fi
fi
